---
- name: Installing node exporter
  hosts: all
  vars_files:
    - vars/create_user_vars.yml
  become: true
  tasks:
    - name: Copying docker compose file
      copy:
        src: docker-node-exporter
        dest: /home/{{username}}/

    - name: Run docker compose
      shell:
        cmd: "docker-compose -f docker-compose.yml up -d "
        chdir: /home/{{username}}/docker-node-exporter/